[packages.aspell]
version = "0.60.8.1"
version_check = "gnu:aspell"
description = "Spell checker"
url = "https://ftpmirror.gnu.org/gnu/aspell/aspell-${version}.tar.gz"
git_url = ""
use_git = false
stage = 9
build_order = 0
build_system = "autotools"
configure_flags = "--disable-static"
provides = ["/usr/bin/aspell", "/usr/lib/libaspell.so"]

[packages.aspell-en]
version = "2020.12.07-0"
version_check = "url:https://ftpmirror.gnu.org/gnu/aspell/dict/en/|aspell6-en-([0-9.-]+)\\.tar"
description = "English dictionary for aspell"
url = "https://ftpmirror.gnu.org/gnu/aspell/dict/en/aspell6-en-${version}.tar.bz2"
source_dir = "aspell6-en-${version}"
stage = 9
build_order = 1
depends = ["aspell"]
build_commands = [
    "./configure",
    "make -j${NPROC}",
    "make DESTDIR=${PKG} install"
]

[packages.attr]
version = "2.5.2"
version_check = "savannah:attr"
description = "Extended filesystem attributes"
url = "https://download.savannah.nongnu.org/releases/attr/attr-${version}.tar.xz"
git_url = "https://git.savannah.gnu.org/git/attr.git"
use_git = false
stage = 3
build_order = 20
build_commands = [
    "./configure --prefix=/usr --disable-static --sysconfdir=/etc --docdir=/usr/share/doc/attr-${version}",
    "make -j${NPROC}",
    "make DESTDIR=${PKG} install"
]

[packages.acl]
version = "2.3.2"
version_check = "savannah:acl"
description = "Access Control Lists"
url = "https://download.savannah.nongnu.org/releases/acl/acl-${version}.tar.xz"
git_url = "https://git.savannah.gnu.org/git/acl.git"
use_git = false
stage = 3
build_order = 21
depends = ["attr"]
build_commands = [
    "./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/acl-${version}",
    "make -j${NPROC}",
    "make DESTDIR=${PKG} install"
]

[packages.autoconf]
version = "2.72"
version_check = "gnu:autoconf"
description = "GNU autoconf"
url = "https://ftpmirror.gnu.org/gnu/autoconf/autoconf-${version}.tar.xz"
git_url = "https://git.savannah.gnu.org/git/autoconf.git"
use_git = false
stage = 4

[packages.automake]
version = "1.18.1"
version_check = "gnu:automake"
description = "GNU automake"
url = "https://ftpmirror.gnu.org/gnu/automake/automake-${version}.tar.xz"
git_url = "https://git.savannah.gnu.org/git/automake.git"
use_git = false
stage = 4

[packages.atk]
version = "2.38.0"
version_check = "gnome:atk"
description = "Accessibility toolkit"
url = "https://download.gnome.org/sources/atk/2.38/atk-${version}.tar.xz"
git_url = "https://gitlab.gnome.org/GNOME/atk.git"
use_git = false
stage = 9
build_order = 5
build_system = "meson"
meson_flags = "-Dintrospection=disabled"

[packages.at-spi2-core]
version = "2.58.3"
version_check = "gnome:at-spi2-core"
description = "Accessibility infrastructure"
url = "https://download.gnome.org/sources/at-spi2-core/2.58/at-spi2-core-${version}.tar.xz"
stage = 9
build_order = 5
build_system = "meson"
depends = ["dbus", "glib", "libX11", "libXi", "libXtst"]
meson_flags = "-Dintrospection=disabled -Dx11=enabled -Dsystemd_user_dir=/tmp --wrap-mode=nodownload"

[packages.alsa-lib]
version = "1.2.15.3"
version_check = "alsa:lib"
description = "ALSA sound library"
url = "https://www.alsa-project.org/files/pub/lib/alsa-lib-${version}.tar.bz2"
git_url = "https://github.com/alsa-project/alsa-lib.git"
use_git = false
stage = 11

[packages.alsa-utils]
version = "1.2.15.2"
version_check = "alsa:utils"
description = "ALSA sound utilities"
url = "https://www.alsa-project.org/files/pub/utils/alsa-utils-${version}.tar.bz2"
git_url = "https://github.com/alsa-project/alsa-utils.git"
use_git = false
stage = 11

[packages.amd-ucode]
version = "20260110"
version_check = "url:https://www.kernel.org/pub/linux/kernel/firmware/|linux-firmware-([0-9]+)\.tar"
description = "AMD CPU microcode (extracted from linux-firmware)"
url = "https://www.kernel.org/pub/linux/kernel/firmware/linux-firmware-${version}.tar.xz"
git_url = ""
use_git = false
stage = 19
# Extract amd-ucode/ directory and create initrd for early loading

[packages.appstream-glib]
version = "0.8.3"
version_check = "github:hughsie/appstream-glib"
description = "AppStream helper library"
url = "https://github.com/hughsie/appstream-glib/archive/refs/tags/appstream_glib_0_8_3.tar.gz"
source_dir = "appstream-glib-appstream_glib_0_8_3"
stage = 8
build_order = 50
build_system = "meson"
depends = ["glib", "gdk-pixbuf", "libarchive", "curl"]
meson_flags = "-Dgtk-doc=false -Dintrospection=false -Dman=false -Drpm=false -Dstemmer=false"
provides = ["/usr/share/gettext/its/metainfo.its"]

[packages.amdgpu-firmware]
version = "20260110"
version_check = "url:https://www.kernel.org/pub/linux/kernel/firmware/|linux-firmware-([0-9]+)\.tar"
description = "AMD GPU firmware (part of linux-firmware)"
url = "https://www.kernel.org/pub/linux/kernel/firmware/linux-firmware-${version}.tar.xz"
git_url = ""
use_git = false
stage = 19
# For AMD integrated graphics if present
