[packages.hwdata]
version = "0.403"
version_check = "github:vcrhonek/hwdata"
description = "Hardware identification databases"
url = "https://github.com/vcrhonek/hwdata/archive/v${version}/hwdata-${version}.tar.gz"
git_url = "https://github.com/vcrhonek/hwdata.git"
use_git = false
stage = 8

[packages.harfbuzz]
version = "12.3.1"
version_check = "github:harfbuzz/harfbuzz"
description = "Text shaping library"
url = "https://github.com/harfbuzz/harfbuzz/releases/download/${version}/harfbuzz-${version}.tar.xz"
git_url = "https://github.com/harfbuzz/harfbuzz.git"
use_git = false
stage = 9
build_order = 3
build_system = "meson"
depends = ["cairo", "freetype", "glib"]
meson_flags = "-Ddocs=disabled -Dintrospection=disabled -Dtests=disabled -Dcairo=enabled -Dfreetype=enabled -Dglib=enabled --wrap-mode=nodownload"
