[packages.qemu-guest-agent]
version = "10.2.0-rc4"
version_check = "github:qemu/qemu"
description = "QEMU guest agent"
url = "https://download.qemu.org/qemu-${version}.tar.xz"
git_url = "https://gitlab.com/qemu-project/qemu.git"
use_git = false
stage = 12

# STAGE 13: Gaming (Steam, Proton, Wine)
