# FPGA/EDA Tools

[packages.yosys]
version = "0.61"
version_check = "github:YosysHQ/yosys"
description = "Yosys Open SYnthesis Suite - RTL synthesis framework"
url = "https://github.com/YosysHQ/yosys/releases/download/${version}/yosys-${version}.tar.gz"
git_url = "https://github.com/YosysHQ/yosys.git"
use_git = false
stage = 15
depends = ["tcl", "readline", "libffi", "python", "zlib"]
build_commands = [
    "make config-gcc",
    "make -j${NPROC} PREFIX=/usr",
    "make PREFIX=/usr DESTDIR=${PKG} install"
]
provides = ["/usr/bin/yosys"]
